---
title: "nc_census"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(janitor)
```

```{r data}
# import 2010 data
block_assignment <- read.csv("nc_baf_2010_weighted.csv")
blocks_weighted <- read.csv("nc_blocks_2010_rc_eth_weighted.csv")
tracts_weighted <- read.csv("nc_tracts_2010_rc_eth_weighted.csv")
counties <- read.csv("nc_county_2010_rc_eth.csv")
places <- read.csv("nc_places_2010_rc_eth.csv")

places <- places %>% 
  mutate(total = as.double(total), white = as.double(white), black = as.double(black), aian = as.double(aian),
         asian = as.double(asian), pi = as.double(pi), other = as.double(other), multi = as.double(multi), 
         hispanic = as.double(hispanic), non_his = as.double(non_his), white_nh = as.double(white_nh),
         black_nh = as.double(black), aian_nh = as.double(aian_nh), asian_nh = as.double(asian_nh),
         pi_nh = as.double(pi_nh), other_nh = as.double(other_nh), multi_nh = as.double(multi_nh))

# specify location
geoheader_path <- "ncgeo2020.pl"
race_ethnicity_path <- "nc000012020.pl"
vap_housing_path <- "nc000022020.pl"
group_quarters_path <- "nc000032020.pl"

# import data
geoheader <- read.delim(geoheader_path, header = F, colClasses = "character", sep = "|")
race_ethnicity <- read.delim (race_ethnicity_path, header = F, colClasses = "character", sep = "|")
vap_housing <- read.delim (vap_housing_path, header = F, colClasses = "character", sep = "|")
group_quarters <- read.delim(group_quarters_path, header = F, colClasses = "character", sep = "|")

# assign column names
colnames(geoheader) <- c("FILEID", "STUSAB", "SUMLEV", "GEOVAR", "GEOCOMP", "CHARITER", "CIFSN", "LOGRECNO", "GEOID", 
                         "GEOCODE", "REGION", "DIVISION", "STATE", "STATENS", "COUNTY", "COUNTYCC", "COUNTYNS", "COUSUB",
                         "COUSUBCC", "COUSUBNS", "SUBMCD", "SUBMCDCC", "SUBMCDNS", "ESTATE", "ESTATECC", "ESTATENS", 
                         "CONCIT", "CONCITCC", "CONCITNS", "PLACE", "PLACECC", "PLACENS", "TRACT", "BLKGRP", "BLOCK", 
                         "AIANHH", "AIHHTLI", "AIANHHFP", "AIANHHCC", "AIANHHNS", "AITS", "AITSFP", "AITSCC", "AITSNS", 
                         "TTRACT", "TBLKGRP", "ANRC", "ANRCCC", "ANRCNS", "CBSA", "MEMI", "CSA", "METDIV", "NECTA", 
                         "NMEMI", "CNECTA", "NECTADIV", "CBSAPCI", "NECTAPCI", "UA", "UATYPE", "UR", "CD116", "CD118",
                         "CD119", "CD120", "CD121", "SLDU18", "SLDU22", "SLDU24", "SLDU26", "SLDU28", "SLDL18", "SLDL22",
                         "SLDL24", "SLDL26", "SLDL28", "VTD", "VTDI", "ZCTA", "SDELM", "SDSEC", "SDUNI", "PUMA", 
                         "AREALAND", "AREAWATR", "BASENAME", "NAME", "FUNCSTAT", "GCUNI", "POP100", "HU100", "INTPTLAT", 
                         "INTPTLON", "LSADC", "PARTFLAG", "UGA")
geoheader <- geoheader %>% 
  clean_names(case = "snake")

colnames(race_ethnicity) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                              paste0("P00", c(10001:10071, 20001:20073)))
race_ethnicity <- race_ethnicity %>% 
  clean_names(case = "snake")

colnames(vap_housing) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", 
                           paste0("P00", c(30001:30071, 40001:40073)), paste0("H00", 10001:10003))
vap_housing <- vap_housing %>% 
  clean_names(case = "snake")

colnames(group_quarters) <- c("FILEID", "STUSAB", "CHARITER", "CIFSN", "LOGRECNO", paste0("P00", 50001:50010))
group_quarters <- group_quarters %>% 
  clean_names(case = "snake")
```

```{r functions}
# generate tables based on summary level
race_ethnicity_table <- function(sumlev_code) {
  geoheader %>% 
    filter(sumlev == sumlev_code) %>% 
    select(logrecno, geocode) %>% 
    left_join(race_ethnicity %>% 
                select(logrecno, p0010001, p0010003, p0010004, p0010005, p0010006, p0010007, 
                       p0010008, p0010009, p0020002, p0020003, p0020005, p0020006, p0020007, 
                       p0020008, p0020003, p0020009, p0020010, p0020011) %>% 
                rename(total = p0010001, white = p0010003, black = p0010004, aian = p0010005, asian = p0010006, 
                       pi = p0010007, other = p0010008, multi = p0010009, hispanic = p0020002, non_his = p0020003, 
                       white_nh = p0020005, black_nh = p0020006, aian_nh = p0020007, asian_nh = p0020008, 
                       pi_nh = p0020009, other_nh = p0020010, multi_nh = p0020011), by = "logrecno") %>% 
    select(-logrecno) %>% 
    mutate(total = as.double(total), white = as.double(white), black = as.double(black), aian = as.double(aian),
           asian = as.double(asian), pi = as.double(pi), other = as.double(other), multi = as.double(multi), 
           hispanic = as.double(hispanic), non_his = as.double(non_his), white_nh = as.double(white_nh),
           black_nh = as.double(black), aian_nh = as.double(aian_nh), asian_nh = as.double(asian_nh),
           pi_nh = as.double(pi_nh), other_nh = as.double(other_nh), multi_nh = as.double(multi_nh))
}

vap_housing_table <- function(sumlev_code) {
  geoheader %>% 
    filter(sumlev == sumlev_code) %>% 
    select(logrecno, geocode) %>% 
    left_join(vap_housing %>% 
                select(logrecno, h0010001, h0010002, h0010003) %>% 
                rename(total = h0010001, occupied = h0010002, vacant = h0010003), by = "logrecno") %>% 
    select(-logrecno) %>% 
    mutate(total = as.double(total), occupied = as.double(occupied), vacant = as.double(vacant))
}

group_quarters_table <- function(sumlev_code) {
  geoheader %>% 
    filter(sumlev == sumlev_code) %>% 
    select(logrecno, geocode) %>% 
    left_join(group_quarters %>% 
                select(logrecno, p0050001, p0050002, p0050003, p0050004, p0050005,
                       p0050006, p0050007, p0050008, p0050009, p0050010) %>% 
                rename(total = p0050001, institution = p0050002, correction = p0050003, juvenile = p0050004,
                       nursing = p0050005, other_ins = p0050006, non_ins = p0050007, college = p0050008, 
                       military = p0050009, other_ni = p0050010), by = "logrecno") %>% 
    select(-logrecno) %>% 
    mutate(total = as.double(total), institution = as.double(institution), correction = as.double(correction), 
           juvenile = as.double(juvenile), nursing = as.double(nursing), other_ins = as.double(other_ins), 
           non_ins = as.double(non_ins), college = as.double(college), military = as.double(military), 
           other_ni = as.double(other_ni))
}

compare_race <- function(table) {
  table %>% 
    pivot_longer(!year, names_to = "race", values_to = "count") %>% 
    arrange(race) %>% 
    group_by(race) %>% 
    mutate(diff = count - lead(count), pct_change = (count / lead(count) - 1) * 100)
}
```

```{r state-analysis}
# https://www2.census.gov/programs-surveys/decennial/rdo/about/2020-census-program/Phase3/SupportMaterials/FrequentSummaryLevels.pdf
# find raw and percent change for each race and total population from 2010 to 2020
nc_race <- race_ethnicity_table("050") %>% 
  summarize(total = sum(total), hispanic = sum(hispanic), white_nh = sum(white_nh), black_nh = sum(black_nh),
            aian_nh = sum(aian_nh), asian_nh = sum(asian_nh), pi_nh = sum(pi_nh), other_nh = sum(other_nh), 
            multi_nh = sum(multi_nh)) %>% 
  mutate(year = 2020) %>% 
  rbind(., counties %>% 
          summarize(total = sum(total), hispanic = sum(hispanic), white_nh = sum(white_nh), black_nh = sum(black_nh),
                    aian_nh = sum(aian_nh), asian_nh = sum(asian_nh), pi_nh = sum(pi_nh), other_nh = sum(other_nh), 
                    multi_nh = sum(multi_nh)) %>% 
          mutate(year = 2010)) %>% 
  pivot_longer(!year, names_to = "race", values_to = "count") %>% 
  arrange(race) %>% 
  group_by(race) %>% 
  mutate(diff = count - lead(count), pct_change = (count / lead(count) - 1) * 100)

# find percentage of new residents who are people of color
nc_race %>% 
  filter(year == 2020) %>% 
  select(race, diff) %>% 
  pivot_wider(names_from = race, values_from = diff) %>% 
  summarize(poc = (asian_nh + black_nh + hispanic + pi_nh) / total)

# for datawrapper
county_pct_change <- counties %>% 
  mutate(year = 2010) %>% 
  rename(geocode = county_id_2010) %>% 
  select(year, geocode, total) %>% 
  rbind(., race_ethnicity_table("050") %>% 
          mutate(year = 2020) %>% 
          select(year, geocode, total)) %>% 
  left_join(geoheader %>% 
              filter(sumlev == "050") %>% 
              select(geocode, basename), by = "geocode") %>% 
  mutate(total = as.double(total), county = basename) %>% 
  select(year, county, total) %>% 
  filter(!is.na(county)) %>% 
  pivot_wider(names_from = year, values_from = total) %>% 
  mutate(pct_change = (`2020` - `2010`) / `2010` * 100)
```

```{r triangle-analysis}
# Durham FIPS: 37063
# Orange FIPS: 37135
# Wake FIPS: 37183
# Chatham FIPS: 37037
triangle_race <- race_ethnicity_table("050") %>% 
  filter(geocode %in% c("37037", "37063","37135", "37183")) %>% 
  summarize(total = sum(total), hispanic = sum(hispanic), white_nh = sum(white_nh), black_nh = sum(black_nh),
            aian_nh = sum(aian_nh), asian_nh = sum(asian_nh), pi_nh = sum(pi_nh), other_nh = sum(other_nh), 
            multi_nh = sum(multi_nh)) %>% 
  mutate(year = 2020) %>% 
  rbind(., counties %>% 
          filter(county_id_2010 %in% c(37037, 37063, 37135, 37183)) %>% 
          summarize(total = sum(total), hispanic = sum(hispanic), white_nh = sum(white_nh), black_nh = sum(black_nh),
                    aian_nh = sum(aian_nh), asian_nh = sum(asian_nh), pi_nh = sum(pi_nh), other_nh = sum(other_nh), 
                    multi_nh = sum(multi_nh)) %>% 
        mutate(year = 2010)) %>% 
  pivot_longer(!year, names_to = "race", values_to = "count") %>% 
  arrange(race) %>% 
  group_by(race) %>% 
  mutate(diff = count - lead(count), pct_change = (count / lead(count) - 1) * 100)

# find percentage of total and new residents who are people of color
triangle_race %>% 
  filter(race == "total", year == 2020) %>% 
  rbind(., nc_race %>% 
          filter(race == "total", year == 2020)) %>% 
  summarize(count_prop = count / lead(count), diff_prop = diff / lead(diff))
```

```{r county-analysis}
oc_race <- race_ethnicity_table("050") %>% 
  mutate(year = 2020) %>% 
  filter(geocode == "37135") %>% 
  select(-geocode) %>% 
  rbind(., counties %>% 
          filter(county_id_2010 == 37135) %>% 
          select(-sumlev, -logrecno, -county_id_2010) %>% 
          mutate(year = 2010)) %>% 
  select(year, total:multi_nh)
compare_race(oc_race)

dc_race <- race_ethnicity_table("050") %>% 
  mutate(year = 2020) %>% 
  filter(geocode == "37063") %>% 
  select(-geocode) %>% 
  rbind(., counties %>% 
          filter(county_id_2010 == 37063) %>% 
          select(-sumlev, -logrecno, -county_id_2010) %>% 
          mutate(year = 2010)) %>% 
  select(year, total:multi_nh)
compare_race(dc_race)

wc_race <- race_ethnicity_table("050") %>% 
  mutate(year = 2020) %>% 
  filter(geocode == "37183") %>% 
  select(-geocode) %>% 
  rbind(., counties %>% 
          filter(county_id_2010 == 37183) %>% 
          select(-sumlev, -logrecno, -county_id_2010) %>% 
          mutate(year = 2010)) %>% 
  select(year, total:multi_nh)
compare_race(wc_race)

cc_race <- race_ethnicity_table("050") %>% 
  mutate(year = 2020) %>% 
  filter(geocode == "37037") %>% 
  select(-geocode) %>% 
  rbind(., counties %>% 
          filter(county_id_2010 == 37037) %>% 
          select(-sumlev, -logrecno, -county_id_2010) %>% 
          mutate(year = 2010)) %>% 
  select(year, total:multi_nh)
compare_race(cc_race)
```

```{r ch-analysis}
# Chapel Hill geocode: 3711800
# Carrboro geocode: 3710620
ch_race <- race_ethnicity_table("160") %>% 
  filter(geocode == "3711800") %>% 
  select(-geocode) %>% 
  mutate(year = 2020) %>% 
  rbind(., places %>% 
          filter(name == "Chapel Hill") %>% 
          select(-sumlev, -logrecno, -place_id_2010, -name) %>% 
          mutate(year = 2010)) %>% 
  select(year, total:multi_nh)

# find percentage of new residents who are people of color
compare_race(ch_race) %>% 
  filter(year == 2020) %>% 
  select(race, diff) %>% 
  pivot_wider(names_from = race, values_from = diff) %>% 
  summarize(poc = (asian_nh + black_nh + hispanic + pi_nh) / total)

# find percentage of total residents who are people of color
ch_race %>% 
  filter(year == 2020) %>% 
  summarize(poc = (asian_nh + black_nh + hispanic) / total)

carrboro_race <- race_ethnicity_table("160") %>% 
  filter(geocode == "3710620") %>% 
  select(-geocode) %>% 
  mutate(year = 2020) %>% 
  rbind(., places %>% 
          filter(name == "Carrboro") %>% 
          select(-sumlev, -logrecno, -place_id_2010, -name) %>% 
          mutate(year = 2010)) %>% 
  select(year, total:multi_nh)
compare_race(carrboro_race)

vap_housing_table("050")
group_quarters_table("050")
```